export const DEPENDENCY_INVENTORY = [
  {
    id: "emo1-local-runtime",
    kind: "runtime",
    participation: "voting",
    invoked_in_demo: true,
    decision_relevant: true,
    note: "In-process EMO1 engine. All $12N3B evaluators execute here.",
  },
  {
    id: "postgres-or-pglite",
    kind: "storage",
    participation: "informational",
    invoked_in_demo: true,
    decision_relevant: false,
    note: "Durable audit ledger. Neon when configured; PGLite in this preview. Storage is not a voting evaluator.",
  },
  {
    id: "xai",
    kind: "model-provider",
    participation: "excluded",
    invoked_in_demo: false,
    decision_relevant: false,
    note: "Not invoked. Not decision-relevant. Listing is inventory, not endorsement.",
  },
  {
    id: "openai",
    kind: "model-provider",
    participation: "excluded",
    invoked_in_demo: false,
    decision_relevant: false,
    note: "Not invoked. Not decision-relevant. Listing is inventory, not endorsement.",
  },
  {
    id: "anthropic",
    kind: "model-provider",
    participation: "excluded",
    invoked_in_demo: false,
    decision_relevant: false,
    note: "Not invoked. Not decision-relevant. Listing is inventory, not endorsement.",
  },
  {
    id: "identity-broker",
    kind: "identity",
    participation: "excluded",
    invoked_in_demo: false,
    decision_relevant: false,
    note: "Demonstration tenant is shared and unauthenticated. Identity services are not in the decision path.",
  },
] as const;
