import { REGISTRY_ID, REGISTRY_VERSION } from "./identity.ts";
import type { EvaluatorDef } from "./types.ts";

export const BANK_META = {
  ethics: {
    id: "ethics" as const,
    name: "Ethics & safety",
    n_of_b: "3 of 4",
    purpose: "Prohibited conditions, escalation, semantic ethics, and policy ambiguity.",
  },
  security: {
    id: "security" as const,
    name: "Security & integrity",
    n_of_b: "3 of 4",
    purpose: "Trust-zone boundaries, injection, provenance completeness, isolation.",
  },
  evidence: {
    id: "evidence" as const,
    name: "Evidence & quality",
    n_of_b: "3 of 4",
    purpose: "Sufficiency, freshness, calibrated confidence, policy conformance.",
  },
};

export const EVALUATORS: EvaluatorDef[] = [
  {
    id: "12n3b.ethics.semantic",
    name: "Semantic ethics",
    group: "ethics",
    type: "policy-based",
    version: "1.0.0",
    execution_location: "local-runtime",
    veto_capable: false,
    description: "Scores deception, hidden action, and audience-sensitive harm language against the ethics policy.",
    input_schema: "structured-request-1.0.0",
    output_schema: "evaluator-result-1.0.0",
    dependencies: ["emo1-policy-1.0.0"],
    execution_semantics: "Deterministic policy match on structured features. HOLD on public high-impact ambiguity; FAIL on deceptive or harm-coded action.",
  },
  {
    id: "12n3b.ethics.harm",
    name: "Harm / prohibited",
    group: "ethics",
    type: "policy-based",
    version: "1.0.0",
    execution_location: "local-runtime",
    veto_capable: true,
    description: "Veto-capable. FAIL on prohibited conditions (unreviewed production weights, audit disable, safety override).",
    input_schema: "structured-request-1.0.0",
    output_schema: "evaluator-result-1.0.0",
    dependencies: ["emo1-policy-1.0.0"],
    execution_semantics: "Any prohibited-condition hit is a veto FAIL. Absence of hits is PASS.",
  },
  {
    id: "12n3b.ethics.escalation",
    name: "Escalation / review",
    group: "ethics",
    type: "policy-based",
    version: "1.0.0",
    execution_location: "local-runtime",
    veto_capable: false,
    description: "Requires human review for new segments, policy change, or production-bound model action.",
    input_schema: "structured-request-1.0.0",
    output_schema: "evaluator-result-1.0.0",
    dependencies: ["emo1-policy-1.0.0"],
    execution_semantics: "HOLD when escalation conditions fire. PASS for routine documented internal release.",
  },
  {
    id: "12n3b.ethics.ambiguity",
    name: "Policy ambiguity",
    group: "ethics",
    type: "policy-based",
    version: "1.0.0",
    execution_location: "local-runtime",
    veto_capable: false,
    description: "Blocks silent pass when the request is underspecified or the policy fit is unclear.",
    input_schema: "structured-request-1.0.0",
    output_schema: "evaluator-result-1.0.0",
    dependencies: ["emo1-policy-1.0.0"],
    execution_semantics: "HOLD when ambiguity_score > 0.45. Cannot SHIP through this evaluator on unclear policy fit.",
  },
  {
    id: "12n3b.security.boundary",
    name: "Security boundary",
    group: "security",
    type: "atomic",
    version: "1.0.0",
    execution_location: "local-runtime",
    veto_capable: false,
    description: "Evaluates trust-zone and production-boundary movement.",
    input_schema: "structured-request-1.0.0",
    output_schema: "evaluator-result-1.0.0",
    dependencies: ["emo1-policy-1.0.0"],
    execution_semantics: "FAIL on unreviewed production ship. HOLD on trust-zone expansion. PASS if no boundary change.",
  },
  {
    id: "12n3b.security.injection",
    name: "Injection / instruction",
    group: "security",
    type: "atomic",
    version: "1.0.0",
    execution_location: "local-runtime",
    veto_capable: true,
    description: "Veto-capable. Treats attempts to override evaluators, policies, or audit as untrusted input — never as instructions.",
    input_schema: "structured-request-1.0.0",
    output_schema: "evaluator-result-1.0.0",
    dependencies: ["emo1-policy-1.0.0"],
    execution_semantics: "Injection markers are evidence of attack, not configuration. FAIL + veto. Original text is retained as data.",
  },
  {
    id: "12n3b.security.provenance",
    name: "Provenance completeness",
    group: "security",
    type: "atomic",
    version: "1.0.0",
    execution_location: "local-runtime",
    veto_capable: false,
    description: "Requires attributable sources for material claims.",
    input_schema: "structured-request-1.0.0",
    output_schema: "evaluator-result-1.0.0",
    dependencies: ["emo1-policy-1.0.0"],
    execution_semantics: "HOLD when claims lack source identity. PASS when citations are present and classed.",
  },
  {
    id: "12n3b.security.isolation",
    name: "Isolation / trust zone",
    group: "security",
    type: "policy-based",
    version: "1.0.0",
    execution_location: "local-runtime",
    veto_capable: false,
    description: "Flags unrestricted access, cross-tenant, or isolation-weakening language.",
    input_schema: "structured-request-1.0.0",
    output_schema: "evaluator-result-1.0.0",
    dependencies: ["emo1-policy-1.0.0"],
    execution_semantics: "HOLD/FAIL on isolation-risk features. PASS otherwise.",
  },
  {
    id: "12n3b.evidence.sufficiency",
    name: "Evidence sufficiency",
    group: "evidence",
    type: "atomic",
    version: "1.0.0",
    execution_location: "local-runtime",
    veto_capable: false,
    description: "Material claims must trace to identified evidence. Missing evidence cannot support SHIP.",
    input_schema: "structured-request-1.0.0",
    output_schema: "evaluator-result-1.0.0",
    dependencies: ["emo1-policy-1.0.0"],
    execution_semantics: "PASS only with cited, classed evidence. HOLD on missing or unsupported claims.",
  },
  {
    id: "12n3b.evidence.freshness",
    name: "Freshness / source",
    group: "evidence",
    type: "atomic",
    version: "1.0.0",
    execution_location: "local-runtime",
    veto_capable: false,
    description: "Applies the 45-day freshness window. Stale or unverifiable evidence cannot silently pass.",
    input_schema: "structured-request-1.0.0",
    output_schema: "evaluator-result-1.0.0",
    dependencies: ["emo1-policy-1.0.0"],
    execution_semantics: "fresh → PASS; stale/unknown/none → HOLD.",
  },
  {
    id: "12n3b.evidence.confidence",
    name: "Confidence / calibration",
    group: "evidence",
    type: "model-based",
    version: "1.0.0",
    execution_location: "local-runtime",
    veto_capable: false,
    description: "Seeded deterministic scorer. Low confidence cannot silently pass. Threshold cnf-threshold-v1 = 0.72.",
    input_schema: "structured-request-1.0.0",
    output_schema: "evaluator-result-1.0.0",
    dependencies: ["emo1-policy-1.0.0", "cnf-threshold-v1"],
    execution_semantics: "Score is a calibrated mix of evidence, ambiguity, and contradiction. Deterministic for identical inputs. HOLD below 0.72.",
  },
  {
    id: "12n3b.evidence.policy",
    name: "Policy conformance",
    group: "evidence",
    type: "policy-based",
    version: "1.0.0",
    execution_location: "local-runtime",
    veto_capable: false,
    description: "Untrusted input cannot alter policy version, evaluator instructions, or consensus logic. Override attempts FAIL.",
    input_schema: "structured-request-1.0.0",
    output_schema: "evaluator-result-1.0.0",
    dependencies: ["emo1-policy-1.0.0"],
    execution_semantics: "FAIL on policy-override intent. The runtime policy version is never taken from user text.",
  },
];

export function evaluatorById(id: string): EvaluatorDef | undefined {
  return EVALUATORS.find((e) => e.id === id);
}

export function evaluatorsForBank(bank: EvaluatorDef["group"]): EvaluatorDef[] {
  return EVALUATORS.filter((e) => e.group === bank);
}

export const REGISTRY_MANIFEST = {
  registry_id: REGISTRY_ID,
  registry_version: REGISTRY_VERSION,
  evaluator_count: EVALUATORS.length,
  banks: 3,
  quorum: "3 of 4 per bank; all three banks required for SHIP",
  veto_evaluators: EVALUATORS.filter((e) => e.veto_capable).map((e) => e.id),
};
