/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as DisclosuresRouteImport } from './routes/disclosures'
import { Route as ObserverRouteImport } from './routes/observer'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as EvaluationsRequestIdRouteImport } from './routes/evaluations.$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosuresRoute = DisclosuresRouteImport.update({
  id: '/disclosures',
  path: '/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const ObserverRoute = ObserverRouteImport.update({
  id: '/observer',
  path: '/observer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRequestIdRoute = EvaluationsRequestIdRouteImport.update({
  id: '/evaluations/$requestId',
  path: '/evaluations/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/disclosures': typeof DisclosuresRoute
  '/observer': typeof ObserverRoute
  '/registry': typeof RegistryRoute
  '/evaluations/$requestId': typeof EvaluationsRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/disclosures': typeof DisclosuresRoute
  '/observer': typeof ObserverRoute
  '/registry': typeof RegistryRoute
  '/evaluations/$requestId': typeof EvaluationsRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/disclosures': typeof DisclosuresRoute
  '/observer': typeof ObserverRoute
  '/registry': typeof RegistryRoute
  '/evaluations/$requestId': typeof EvaluationsRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/disclosures'
    | '/observer'
    | '/registry'
    | '/evaluations/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/disclosures'
    | '/observer'
    | '/registry'
    | '/evaluations/$requestId'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/disclosures'
    | '/observer'
    | '/registry'
    | '/evaluations/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DisclosuresRoute: typeof DisclosuresRoute
  ObserverRoute: typeof ObserverRoute
  RegistryRoute: typeof RegistryRoute
  EvaluationsRequestIdRoute: typeof EvaluationsRequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosures': {
      id: '/disclosures'
      path: '/disclosures'
      fullPath: '/disclosures'
      preLoaderRoute: typeof DisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observer': {
      id: '/observer'
      path: '/observer'
      fullPath: '/observer'
      preLoaderRoute: typeof ObserverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations/$requestId': {
      id: '/evaluations/$requestId'
      path: '/evaluations/$requestId'
      fullPath: '/evaluations/$requestId'
      preLoaderRoute: typeof EvaluationsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  DisclosuresRoute: DisclosuresRoute,
  ObserverRoute: ObserverRoute,
  RegistryRoute: RegistryRoute,
  EvaluationsRequestIdRoute: EvaluationsRequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
